OnlineCoupone.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCoupone.DAL.Repository;
using OnlineCoupone.Model.ModelDB;

namespace OnlineCoupone.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

OnlineCoupone.Web/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCoupone.DAL.Repository;

namespace OnlineCoupone.Web.Controllers
{
    public class RegionController : Controller
    {
        public ActionResult Index(int regionId)
        {
            ViewBag.RegionId = regionId;
            var repository = new Repository();
            ViewBag.Region = repository.GetRegionById(regionId);
            ViewBag.Policlinics = repository.GetPoliclinicsByRegionId(regionId);
            return View();
        }
	}
}

OnlineCoupone.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OnlineCoupone.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineCoupone.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная страница";
}

<div class="jumbotron green">
    <h2>Online заказ талонов</h2>
    <p class="lead">Вы можете заказать какой угодно талон совершенно бесплатно.</p>
    <p><a href="/about" class="btn blue btn-large">Узнать подробнее &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Выберите регион</h2>
        <table class="table orange">
            <tr>
                <td>
                    
                </td>
                <td>
                    <a class="lead" href="@Url.Action("Index", "Region", new { regionId = 7 })">Минск</a>
                </td>
                <td>
                </td> 
            </tr>
            <tr>
                <td>
                    <a class="lead" href="@Url.Action("Index", "Region", new { regionId = 1 })">Брестская обл.</a>
                </td>
                <td>
                    <a class="lead" href="@Url.Action("Index", "Region", new { regionId = 2 })">Витебская обл.</a>
                </td>
                <td>
                    <a class="lead" href="@Url.Action("Index", "Region", new { regionId = 3 })">Гомельская обл.</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a class="lead" href="@Url.Action("Index", "Region", new { regionId = 4 })">Гродненская обл.</a>
                </td>
                <td>
                    <a class="lead" href="@Url.Action("Index", "Region", new { regionId = 5 })">Минская обл.</a>
                </td>
                <td>
                    <a class="lead" href="@Url.Action("Index", "Region", new { regionId = 6 })">Могилевская обл.</a>
                </td>
            </tr>
        </table>
    </div>
</div>