OnlineCoupone.Web/Controllers/MyTalonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCoupone.DAL.Repository;

namespace OnlineCoupone.Web.Controllers
{
    public class MyTalonController : Controller
    {
        //
        // GET: /MyTalon/
        public ActionResult Index(int policlinicId)
        {
            ViewBag.PoliclinicId = policlinicId;
            return View();
        }

        public ActionResult History(int policlinicId, int patientId)
        {
            var repository = new Repository();
            var histories = repository.GetAllVisitsByPateientIdAndPoliclinicId(patientId, policlinicId);
            ViewBag.PoliclinicId = policlinicId;
            ViewBag.PatientId = patientId;
            ViewBag.Histories = histories;
            return View();
        }

        public ActionResult HomeVisitHistory(int policlinicId, int patientId)
        {
            var repository = new Repository();
            var homeVisitHistories = repository.GetHomeVisitHistoriesByPatientIdAndPoliclinicId(policlinicId, patientId);
            ViewBag.PoliclinicId = policlinicId;
            ViewBag.PatientId = patientId;
            ViewBag.Histories = homeVisitHistories;
            return View();
        }

        public ActionResult CancelOrder(int policlinicId, int patientId, int visitHistoryId)
        {
            var repository = new Repository();
            var history = repository.GetVisitHistoryById(visitHistoryId);
            repository.SetUnusedAvailableTimeById(history.AvailableTime.AvailableTimeId);
            repository.DeleteVisitHistory(visitHistoryId);
            return RedirectToAction("History", new {policlinicId = policlinicId, patientId = patientId});
        }

        public ActionResult CancelHomeOrder(int policlinicId, int patientId, int homeVisitHistoryId)
        {
            var repository = new Repository();
            repository.DeleteHomeVisitHistory(homeVisitHistoryId);
            return RedirectToAction("HomeVisitHistory", new {policlinicId = policlinicId, patientId = patientId});
        }

	}
}

OnlineCoupone.Web/Views/MyTalon/History.cshtml
@{
    ViewBag.Title = "History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page-title">История</h2>

<a disabled class="btn darker-green black">История заказов талонов</a>
<a href="@Url.Action("HomeVisitHistory", "MyTalon", new {policlinicId = ViewBag.PoliclinicId, patientId = ViewBag.PatientId})" class="btn green black">История вызова врача</a>

<table class="table table-hover orange">
    @for (var i = 0; i < ViewBag.Histories.Count; i++)
    {
        <tr>
            <td>@ViewBag.Histories[i].Doctor.Fio</td>
            <td>@ViewBag.Histories[i].Doctor.Specialization.Name</td>
            <td>@ViewBag.Histories[i].AvailableTime.Time</td>
            <td><a href="@Url.Action("CancelOrder", "MyTalon", new { policlinicId = ViewBag.PoliclinicId, patientId = ViewBag.PatientId, visitHistoryId = ViewBag.Histories[i].VisitHistoryId })" class="btn btn-sm btn-danger">Cancel</a></td>
        </tr>
    }
</table>

OnlineCoupone.Web/Views/MyTalon/HomeVisitHistory.cshtml
@{
    ViewBag.Title = "HomeVisitHistory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page-title">История вызова врача</h2>

<a href="@Url.Action("History", "MyTalon", new { policlinicId = ViewBag.PoliclinicId, patientId = ViewBag.PatientId }) " class=" btn green black">История заказов талонов</a>
<a disabled class="btn darker-green black">История вызова врача</a>

<table class="table table-hover orange">
    @for (var i = 0; i < ViewBag.Histories.Count; i++)
    {
        <tr>
            <td>@ViewBag.Histories[i].Policlinic.Title</td>
            <td>@ViewBag.Histories[i].Date</td>
            <td><a href="@Url.Action("CancelHomeOrder", "MyTalon", new { policlinicId = ViewBag.PoliclinicId, patientId = ViewBag.PatientId, homeVisitHistoryId = ViewBag.Histories[i].HomeVisitHistoryId })" class="btn btn-sm btn-danger">Cancel</a></td>
        </tr>
    }
</table>

OnlineCoupone.Web/Views/MyTalon/Index.cshtml
@{
    ViewBag.Title = "История заказов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page-title">История заказов</h2>

<div id="patient_form" class="container">
    <div class="form-group col-sm-12">
        <label for="" class="col-sm-3 control-label">
            Last name*
        </label>
        <div class="col-sm-9">
            <input type="text" class="form-control" value="" id="lastName" required="required" />
        </div>
    </div>
    <div class="form-group col-sm-12">
        <label for="" class="col-sm-3 control-label">
            Name*
        </label>
        <div class="col-sm-9">
            <input type="text" class="form-control" value="" id="name" required="required" />
        </div>
    </div>
    <div class="form-group col-sm-12">
        <label for="" class="col-sm-3 control-label">
            Patronymic*
        </label>
        <div class="col-sm-9">
            <input type="text" class="form-control" value="" id="patronymic" required="required" />
        </div>
    </div>
    <div class="form-group col-sm-12">
        <label for="" class="col-sm-3 control-label">
            Birthday*
        </label>
        <div class="col-sm-9">
            <input type="date" class="form-control" value="" id="birthday" required="required" />
        </div>
    </div>
    <div class="form-group col-sm-12">
        <label for="" class="col-sm-3 control-label">
            Address*
        </label>
        <div class="col-sm-9">
            <input type="text" class="form-control" value="" id="address" required="required" />
        </div>
    </div>
    <div class="form-group col-sm-5">
        <button id="continue" class="btn btn-primary">Continue</button>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#continue').click(function() {
            debugger;
            var patient = {};
            patient.LastName = $("#lastName").val();
            patient.FirstName = $("#name").val();
            patient.Patronymic = $("#patronymic").val();
            patient.Birthday = $("#birthday").val();
            patient.Address = $("#address").val();
            $.ajax({
                type: 'POST',
                url: '/Validate/ValidateUser',
                data: JSON.stringify({ 'patient': patient}),
                contentType: 'application/json',
                success: function (result) {
                    if (result == '-1') {
                        alert("Отсутствует такой пользователь!");
                    } else {
                        window.location = '/myTalon/history?policlinicId=@ViewBag.PoliclinicId&patientId=' + result;
                    }
                },
                error: function (error) {
                    alert("Error!");
                }
            });
        });
    });
</script>