OnlineCoupone.Web/Controllers/PoliclinicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCoupone.DAL.Repository;

namespace OnlineCoupone.Web.Controllers
{
    public class PoliclinicController : Controller
    {
        //
        // GET: /Policlinic/
        public ActionResult Index(int policlinicId)
        {
            ViewBag.PoliclinicId = policlinicId;
            var repository = new Repository();
            ViewBag.Policlinic = repository.GetPoliclinicById(policlinicId);
            return View();
        }
	}
}

OnlineCoupone.Web/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCoupone.DAL.Repository;

namespace OnlineCoupone.Web.Controllers
{
    public class RegionController : Controller
    {
        public ActionResult Index(int regionId)
        {
            ViewBag.RegionId = regionId;
            var repository = new Repository();
            ViewBag.Region = repository.GetRegionById(regionId);
            ViewBag.Policlinics = repository.GetPoliclinicsByRegionId(regionId);
            return View();
        }
	}
}

OnlineCoupone.Web/Views/Region/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr/>
<h2 class="page-title">Выберите поликлинику</h2>
<h4> @ViewBag.Region.Name</h4>
<ul class="flex-list orange">
    @for (var i = 0; i < ViewBag.Policlinics.Count; i++)
    {
        <li>
            <a href="@Url.Action("Index", "Policlinic", new {policlinicId = ViewBag.Policlinics[i].PoliclinicId})">@ViewBag.Policlinics[i].Title</a>
        </li>
    }
</ul>